image: Ubuntu1804
stack: node 16
cache: node_modules
branches:
  only:
    - main
install: yarn
build: off
build_script: yarn run build
deploy_script:
  - git config --global credential.helper store
  - git config --global user.name GaliullinAR
  - git config --global user.email galiullin.ar651@gmail.com
  - echo "https://$GITHUB_TOKEN:x-oauth-basic@github.com" > "$HOME/.git-credentials"
  - npx push-dir --dir=dist --branch=gh-pages --force --verbose